### ISSUE TITLE
war command: build from working copy

### ISSUE THREAD

**Issue by bemson** [aversini/fedtools#43]
By default, the `war` command depends on a remote branch. Allowing this to build from the local working-copy would be ideal, as it avoids unnecessary commits and pushes.

If possible, the flow of this command could assume more about where to build from, and simply require a destination directory.

The prompts and pulling of the yui3 branch may still be necessary, but it'd be nice to avoid if possible.

**Comment by aversini** [comment]
Version 1.0.13 fixes this request. You need to set the configuration flag "cloneorlocal" to true though:
```
fedtools config set cloneorlocal true
```

**Comment by gurumvg** [comment]
@aversini , Also would be nice to build the pushed code locally rather than at jenkins / warbuilder server.

cc: @bemson
