### ISSUE TITLE
Implement "cache" flag during local build

### ISSUE THREAD

**Issue by bemson** [aversini/fedtools#52]
The build command (wb) should now set the a new "cache" flag in _shifter.json_ to `false`. The command option "--cache" would enable overriding this default behavior.

Forthcoming updates to _yui.js_ will take advantage of this flag's value, to control client-side module caching.

**Comment by aversini** [comment]
Fixed in v1.0.110.
fedtools wb will change the value of the key "replace_wf2-cache" to "false" but default.
fedtools wb --cache will change it to true
